### PR TITLE
Update 99governor

### PR DESCRIPTION
**Pull request by Smacksmack206**
Noticed that when I was checking CPU statistics I was showing the most used frequency on LITTLE Cluster was 1593MHz, Also noticed the associated battery drains from this. Added 307MHZ Target load to LITTLE Cluster and Also changed the Input boost to have LITTLE Cluster firing at lowest frequency 307MHz for CPU cores 0-3.

@Alcolawl @NYCHitman1
can yall check this out for me how is it looking? any feedback you could possible throw me? I appreciate it fam

### CODE REVIEW

**Comment by nychitman1** [comment]
What chipset does your device use?

**Comment by Smacksmack206** [comment]
Good looking fam, my device uses Snapdragon 820 Quad Core Kyro 
Little Cluster seems to be max at 1593600
While the Big Cluster is Max at 2150400
I appreciate it

**Comment by nychitman1** [comment]
FWIW, @Alcolawl and I designed DrunkSauce with 808/810 in mind.

With that said, I'm sure it's likely just something small you're missing here. Would it be possible to get a list of your accessible freqs?

**Comment by Smacksmack206** [comment]
gotcha I loved drunksauce on my nexus 5x with the 808.
my frequency list I got for the Xperia XZ is as following 
Little Cluster: 307mhz, 480mhz, 652mhz, 844mhz, 960mhz, 1113mhz, 1228mhz, 1401mhz, 1593mhz.

Big Cluster:  307200, 403mhz, 480mhz, 566mhz, 652mhz, 729mhz, 806mhz, 883mhz, 940mhz, 1036mhz, 1113mhz, 1248mhz, 1324mhz, 1401mhz, 1478mhz, 1555mhz, 1632mhz, 1708mhz, 1785mhz, 1824mhz, 1920mhz, 2073mhz, 2150mhz

**Comment by nychitman1** [comment]
Do you have a device tree on Github?

**Comment by Smacksmack206** [comment]
Nah I'm new to github. do you need me to compile one how would I build one? sorry for the beginner questions

**Comment by nychitman1** [comment]
Well, I mean.. how are you using this profile if you don't have a device tree?

Putting it in EXKM?

**Comment by Smacksmack206** [comment]
I been using it in the init.d folder is system partition under system/etc/init.d 
I have all my scripts running at boot and a test log shows up at the data partition showing if init d is working and what time it started usually as soon as it boots. It's a good way to check what time I turned on my phone from last reboot too lol

**Comment by Smacksmack206** [comment]
I also have EXKM installed on my phone but mainly for stats and enabling other kernel features

**Comment by Alcolawl** [comment]
Sorry gents, was on vacation for the past week. I read through the thread and took a quick look at the 99governor script but didn't read it in much detail yet, so bare with me. 

The main reason for the scripts on the Nexus 5X (or any SD808 device) were to increase battery life while maintaining a smooth UX. I can criticize the 808/810 all day but the CPUs were not as efficient as people initially hoped (it was a rushed project to boot). There are also clock speeds on those chips that are downright useless. Some of them use the same core voltage as two clock speeds below it. The HMP scheduler is also a major pain. The scripts and profiles were a way to make the CPU operate more efficiently, which is why there were actual noticeable gains to be had.

The SD820/1 is a whole different ballgame. The power consumption of the CPU clusters increases much more linearly as clock speeds increases rather than exponentially. Chances are that if the CPU is at a certain clock speed, it most likely needs to be there. Now, if you wish to change how the CPU behaves (more efficient, less aggressive ramping up in clock speeds, etc.) you can certainly do that, but what I'm getting at here is that you need a goal in mind. I didn't see anything mentioned about what you're trying to accomplish with this script, which is why I barely looked at it. I need to know what you want to accomplish. With the SD808/810 it was clear that things could be streamlined without sacrificing too much (if anything at all). The SD820/1 might be more challenging.

**Side note:** I believe someone tried doing this with the HTC 10, I gotta find the thread. He PM'd me a few times on XDA to pick my brain and I think he's had some success. Honestly, I just wish more phones, including Xperia XZ had the Sched governor and Energy Aware scheduling that my Pixel XL does. It's fantastic.

**Comment by Smacksmack206** [comment]
My goal was to have the same battery efficiency gains that I noticed using your scripts on my Nexus 5x, it was perfect imo in the way that I didn't sacrifice performance to achieve crazy battery life. It seems like the 820 is a different ballgame indeed but it seems that it's hard to get bad performance out of it even at low frequencies, you guys are the experts so I trust your input entirely because I don't know shit lol. So even if we could simply have it streamline in a similar fashion I feel it would possibly have good results, also feel as though maybe some settings and values that were in the 808 script wont be need in the 820 since there different imo that would be the challenge is figuring out what needs to be tweaked and what can be over looked. Their was a post on XDA in the Xperia XZ community threads of a guy making a script based off of butterfly gov. I never was much of a fan of butterfly on my Nexus 5x over having drunksauce but from me imitating the frequencies he used to port butterfly to XZ I did the same idea with drunksauce copying some of the values and testing them day by day so far. Was interesting is on his script he screenshoted 9hr SOT but testing his script on my userspace shows different and I have better results with my script. I feel like with both of your help Drunksauce would kick ass on 820 just like on the 808.and since you mentioned that im now on the look for the HTC 10 drunksauce port. I appreciate all the help y'all ✊✊ PS: How would I go about incorporating Energy Aware Scheduling as I see its in some HTC 10 kernels as well as your Pixel?

**Comment by Smacksmack206** [comment]
Progress so far is good this is from 3/13/17: this morning came a long way from CPU being at highest freq most of the time like in commit from Last Thursday 03/08/17, as seen below in screenshots
drunksauce port progress as of 3 13 2017

**Comment by Smacksmack206** [comment]
This is from last Thurday's Commit at 03/09/17
drunksauce port progress as of 3 09 2017

**Comment by Smacksmack206** [comment]
This was the commit from last Wednesday and as you can see this was bad, and ive mad a lot of progress since then
drunksauce port progress as of 3 08 2017

**Comment by Alcolawl** [comment]
Looks like I'm going to be off from work tomorrow and possible wednesday due to this massive snowstorm hitting the Northeast. I'll dive into the SD820's power consumption and clock speeds and read through your script more carefully to see if there are any further tweaks to be made. Looks like you're making good progress regardless. :D 

As far as EAS goes, I'm not really sure. That's more @nychitman1 's forte. I believe it was ported over to the OP3/OP3T, which, I'm assuming, would be a great starting point for any SD820 device.

**Comment by Smacksmack206** [comment]
@nychitman1 @Alcolawl 
Thank you so much, I usually try to be on Github while I'm at work when I finished all my administrative work so I should be able to reply quick. I'm super pumped I got both of yall support on this I appreciate yall fam

**Comment by nychitman1** [comment]
EAS support is a lot of work. The only thing working in your favor is the fact that your device more than likely runs a 3.18.y kernel.

**Comment by Smacksmack206** [comment]
It is running a 3.18 kernel, you must be psychic.

**Comment by nychitman1** [comment]
@Smacksmack206 Here's where it gets complicated. In order for this to work, you're going to need to set up a Linux distro that is set up for an Android build environment.

https://raw.githubusercontent.com/nathanchance/Android-Tools/master/Guides/Building_AOSP.txt

Once you've done that, you'll need to parse through Pixel's kernel source to pull out all of the EAS-related code (which I may add is A LOT).

https://github.com/android/kernel_msm/tree/android-msm-marlin-3.18-nougat-mr1-eas-experimental

**_PS: This is all assuming that you have access to this device's kernel source, which you can modify._**

**Comment by Smacksmack206** [comment]
Gonna look everything over and set up the build environment in order to get started on EAS. in the meantime how is the 99governor in your opinion, given that its 820 is there anything you would potentially add to the commit if it was you trying to set it up on your own device with a 820?

**Comment by nychitman1** [comment]
It looks OK to me, but I would disable input boost altogether if you're just going to have the values set to zero.

@Alcolawl -- what do you think, T-Dawgz?

**Comment by Smacksmack206** [comment]
I'm using window 10 for my personal laptop is it safe to say I can set up my environment in a virtual machine set up of linux?

**Comment by nychitman1** [comment]
@Smacksmack206 Yes, it is possible. However, I personally would not recommend going that route.

**Comment by Alcolawl** [comment]
Just took a look at the script. Everything looks good from here. It seems like, from the frequency usage graphs you've posted, that you're getting the battery-sipping behavior you want out of the phone. I thought the hispeed_freq set to the minimum frequency was a bit of an odd choice but if you're going for maximum battery savings then that's the way to go. As for input boost, just disable it, as NYCHitman1 said.

There is, however, one glaring redundancy in the logic for setting the target_loads for the LITTLE Cluster. Lines 28-44. It starts by grabbing the maximum achievable frequency for that cluster, then checks to see if it's equal to 1593600. If it is, it sets the maximum frequency to 1593600 and then sets the appropriate target_loads. This is fine. Afterwards, though, it basically runs the same check again, which isn't needed, obviously. So you can basically delete lines 37-43. You might be able to get away with deleting all of the logic for the LITTLE cluster and just set the target_loads and maximum frequency. The reason why that logic is even there is because some kernels for the N5X enabled overclocking the clusters (from 1440mhz to 1632mhz) whereas on the SD820 it seems that 1593mhz is the standard max frequency for the LITTLE cluster.

**Comment by Smacksmack206** [comment]
Gotcha, looks like I got some clean up to do on those lines. And yeah I set hi speed to lowest frequency in hopes that it would mostly use tjat freq and save battery, I was hoping i wasnt shooting my self in the foot with all the little cluster settings. Imma try to get a few hours rest cuz I feel under the weather but I'm gonna get started on fixing the script and setting the build environment on my PC. You guys are the best I really appreciate the help

**Comment by Smacksmack206** [comment]
And @nychitman1 I'll set up Linux thru a dual boot then?

**Comment by Smacksmack206** [comment]
@nychitman1 @Alcolawl Got a better question, are anyone of you familiar with WUBI distro? am I able to build with that? It seems like with WUBI I'm able to use the latest Ubuntu 16.10 ISO and can also use 16.04.2 LTS. which would be the most preferred build of Ubuntu? I was gonna try to set it up on my pc at lunch or when I get home for work since I feel alittle better from eating a gang of pills ahahaha

**Comment by nychitman1** [comment]
@Smacksmack206 Sorry, I don't know anything about WUBI. I use Linux Mint.

**Comment by Smacksmack206** [comment]
got mint installed and finishing up the build environment. got mint dual booted with windows

**Comment by Smacksmack206** [comment]
Got mint installed with Windows as primary on dual boot. Just need to connect Ethernet to download drivers for wifi and ECT to start creating build environment

**Comment by Smacksmack206** [comment]
ran into a problem when i was downloading from repo last night with the force sync command and fell asleep with my laptop not attached to power supply so i woke up with me not able to log in to linux from MDM error from space or something. unistalled and now reinstalling with 100gb usb and will attempt to install with out wubi. as wubi gave me a 30gb install limit

**Comment by nychitman1** [comment]
@Smacksmack206 100GB is pretty damn small. Hell, source alone has to be at least 60GB. That doesn't include all the extra stuff you'll need like packages, device specific repos, etc..

**Comment by Smacksmack206** [comment]
Yeah so my best bet is to resize windows partitions on my machine? I got about 150 GB left the HDD. If that isn't enough applicable space either would I have to remove windows entirely? It should have 500gb as a total but I'm showing 297gb probably from other times I was messing with partition from awhile ago

**Comment by Smacksmack206** [comment]
I might do something easier like buy a 2in1 for using Windows on the go which I was think about doing anyway next week. And make this current 8/GB ram i5 laptop for Linux only, with only Linux on the SSD should have enough to space to build

**Pull request merged**
